config/routes.rb
Zhaiwuzhuitao::Application.routes.draw do

  resources :messages

  devise_for :users
  resources :blogs, path: "内容"

  get "/pages/*id" => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'home'
  get "sitemap" => "sitemaps#index"

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name
  validates_presence_of :name, :content
  validates :name, uniqueness: true

  has_ancestry
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :name, :email
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.order("updated_at DESC").all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:name, :summary, :keyword, :content, :weight, :parent_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [ :index, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    respond_to do |format|
      if @message.save
        MessageMailer.send_email(@message).deliver
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render action: 'show', status: :created, location: @message }
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:name, :email, :phone, :note)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include HighVoltage::StaticPage
end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
  layout nil

  def index
    headers['Content-Type'] = 'application/xml'
    @blogs = Blog.all
    @static_pages = []
    respond_to do |format|
      format.xml 
    end
  end
end

app/helpers/application_helper.rb
# -*- coding: utf-8 -*-
module ApplicationHelper
  def markdown(text)
    options = {
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }
    
    extensions = {
      autolink: true,
      superscript: true,
      disable_indented_code_blocks: true
    }
    
    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    
    markdown.render(text).html_safe
  end

  def title(title = nil)
    if title.present?
      content_for :title, title
    else
      content_for?(:title) ? content_for(:title) + ' | 在俄罗斯债务追讨' : APP_CONFIG['default_title']
    end
  end

  def meta_keywords(tags = nil)
    if tags.present?
      content_for :meta_keywords, tags
    else
      content_for?(:meta_keywords) ? content_for(:meta_keywords) : APP_CONFIG['default_keywords']
    end
  end

  def meta_description(description = nil)
    if description.present?
      content_for :meta_description, description
    else
      content_for?(:meta_description) ? content_for(:meta_description) : APP_CONFIG['default_description']
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_form.html.haml
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:"
      %ul
        - @blog.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, {required: ''}
  .field
    = f.label :summary
    = f.text_field :summary
  .field
    = f.label :content
    = f.text_area :content, {required: ''}
  .field
    = f.label :keyword
    = f.text_field :keyword
  .field
    = f.label :weight
    = f.text_field :weight
  .field
    = f.label :parent_id
    = f.collection_select :parent_id, Blog.order(:name), :id, :name, include_blank: true
  .actions
    = f.submit 'Save'

app/views/blogs/edit.html.haml
%h1 Editing blog

= render 'form'

= link_to 'Show', @blog
\|
= link_to 'Back', blogs_path

app/views/blogs/index.html.haml
%header
  %h1 博客列表
  %hr

- @blogs.each do |blog|
  %h3= link_to blog.name, blog_path(blog)
  %p= markdown(truncate(blog.content, length: 200))
  %p.small= blog.updated_at
  - if user_signed_in?
    .manage
      = link_to 'Show', blog, class: "button success tiny"
      = link_to 'Edit', edit_blog_path(blog), class: "button tiny" 
      = link_to 'Destroy', blog, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "button tiny alert"  


= link_to 'New Blog', new_blog_path, class: "button success" if user_signed_in?

app/views/blogs/new.html.haml
%h1 New blog

= render 'form'

= link_to 'Back', blogs_path

app/views/blogs/show.html.haml
- title @blog.name
- meta_description @blog.summary 
- meta_keywords @blog.keyword
= notice

%h1= @blog.name
= markdown(@blog.content)

- if user_signed_in?
  = link_to 'Edit', edit_blog_path(@blog)
  \|
  = link_to 'Back', blogs_path

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53473161-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_bottom.html.haml
.bottom
  .row
    .panel
      = render "pages/quote"

app/views/layouts/_footer.html.haml
%footer.footer
  .row
    .columns.small-12.medium-7
      %h3 联系方式
      %ul.no-bullet
        %li 俄罗斯清关公司
        %li 电话/ 传真: +7 (812) 64 323 62
        %li 地址：191186, 圣彼得堡, 涅夫斯基车道22
    .columns.small-12.medium-5
      %h3 请你跟我们走 
      %p= social_share_button_tag(root_path)

app/views/layouts/_top.html.haml
.secondary-hero

app/views/layouts/_topbar.html.haml
%header#topbar.row
  %nav.top-bar{"data-topbar" => ""}
    %ul.title-area
      %li.name
        %h1= link_to "俄罗斯清关", root_path
      %li.toggle-topbar.menu-icon= link_to "Menu"
    %section.top-bar-section
      / Right Nav Section
      %ul.right
        %li.active= link_to "首页", root_path
        -# - Blog.order("weight asc").all.each do |blog|
        -#   %li= link_to blog.name, blog_path(blog)
        - Blog.order(weight: :asc).roots.each do |blog|
          - if blog.children.present?
            %li{class: "has-dropdown"}
              = link_to blog.name, "#", class: "has-dropdown"
              %ul{class: "dropdown"}
                - blog.children.order(weight: :asc).each do |children|
                  %li= link_to children.name, children
          - else
            %li= link_to blog.name, blog_path(blog)

app/views/layouts/analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53473161-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.haml
!!! 5
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    = favicon_link_tag
    %title= title
    %meta{ name: 'keywords', content: meta_keywords } 
    %meta{ name: 'description', content: meta_description }
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    = render "layouts/topbar"
    .bg{class: controller_name}
      = content_for?(:top) ? yield(:top) : render("layouts/top")
      %main.main{class: controller_name}
        .row 
          .small-12.columns
            = yield
      = content_for?(:bottom) ? yield(:bottom) : render("layouts/bottom")
      = render "layouts/footer"
    = render "layouts/analytics"

    = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/messages/_form.html.haml
= form_for @message do |f|
  - if @message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name, '姓名'
    = f.text_field :name, {required: '', placeholder: '姓名'}
  .field
    = f.label :email, '电子邮件'
    = f.text_field :email, {required: '', placeholder: "yourname@example.biz"}
  .field
    = f.label :phone, '电话'
    = f.text_field :phone, {placeholder: "18688883692"}
  .field
    = f.text_area :note, {required: '', placeholder: "你的留言"}
  .actions
    = f.submit 'Send', class: 'button success radius'

app/views/messages/edit.html.haml
%h1 Editing message

= render 'form'

= link_to 'Show', @message
\|
= link_to 'Back', messages_path

app/views/messages/index.html.haml
%h1 Listing messages

%table
  %tr
    %th Name
    %th Email
    %th Phone
    %th Note
    %th
    %th
    %th

  - @messages.each do |message|
    %tr
      %td= message.name
      %td= message.email
      %td= message.phone
      %td= message.note
      %td= link_to 'Show', message
      %td= link_to 'Edit', edit_message_path(message)
      %td= link_to 'Destroy', message, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Message', new_message_path

app/views/messages/new.html.haml
%h1 你的要求

= render 'form'

app/views/messages/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @message.name
%p
  %b Email:
  = @message.email
%p
  %b Phone:
  = @message.phone
%p
  %b Note:
  = @message.note

= link_to 'Edit', edit_message_path(@message)
\|
= link_to 'Back', messages_path

app/views/pages/_promo.html.haml
.row.promo
  .columns.small-12.medium-4
    = link_to Blog.find_by_name("俄罗斯海运") do
      %h1.green-color 海关清关
      %p 报关清关的问题是对外运输的最常见的问题。我们公司保证又尽快又不贵的办理海关手续。我司提供办理海关手续的全服务。
  .columns.small-12.medium-4
    = link_to Blog.find_by_name("俄罗斯清关费用") do
      %h1.red-color 清关服务
      %p 我们提供注册所需的配套，成本，运输，报关文件（包括翻译和公证）; 我们提供货物住宿，货物临时存储（在莫斯科，圣彼得堡;
  .columns.small-12.medium-4
    = link_to Blog.find_by_name("俄罗斯海运") do
      %h1.yellow-color 俄罗斯货运
      %p 我们公司提供组织实施国际货物运输。国际货运是我们活动的主要方向之一，也是进口和出口清关手续。国际货运是一个复杂的:

app/views/pages/_quote.html.haml
.row
  .quote
    .row
      .columns.small-4.medium-3
        .circle
          %a 
            %i.fi-lightbulb
      .columns.small-8.medium-9
        %h2 物流和海关的问题免费咨询
        %ul.inline-list 
          %li
            %a{href: "mailto:info@germes-trans.com"} info@germes-trans.com
          %li
            %p 007 (812) 64 323 62 

app/views/pages/_thumb.html.haml
.row
  .thumb
    .row
      .columns.small-12.medium-4
        = link_to Blog.find_by_name("俄罗斯货运") do
          %h2 公路运输
          %p= image_tag "thumb/car.jpg", class: "th"
      .columns.small-12.medium-4
        = link_to Blog.find_by_name("俄罗斯空运") do
          %h2 空中运输
          %p= image_tag "thumb/airplane.jpg", class: "th"
      .columns.small-12.medium-4
        = link_to Blog.find_by_name("俄罗斯海运") do
          %h2 水上运输
          %p= image_tag "thumb/boat.jpg", class: "th"

app/views/pages/_top.html.haml
.row.hero
  %ul.example-orbit{data: {orbit: "", options: "animation: slide; bullets: false; paus_on_hover: false;"}}
    %li= image_tag("slides/slide-1.jpg")
    %li= image_tag("slides/slide-2.jpg")
    %li= image_tag("slides/slide-3.jpg")

app/views/pages/home.html.haml
- content_for :top do
  = render "top"
  = render "promo"
  = render "quote"
  = render "thumb"

- content_for :bottom do
  .bottom

%h1 交付和 报关交钥匙 俄罗斯清关公司。
%p 俄罗斯清关公司提供服务，运输和清关来自东南亚，欧洲和北美。   来自东欧和中欧商品的运输和清关需要长达5天，从西欧长达9天， 来自东南亚和北美（美国，加拿大）36至45天。  也可以快递通过空运，交货期限是 2〜3天。
%p 货物通关产自啊海关职位波罗的海，圣彼得堡和普尔科沃海关，中央消费税海关（CAT）的消费税西北办事处。我们保证货物的完整性和安全性 在清关，仓储保税仓库，我们保证操作的性能上的内部端口转发。 «Hermes»公司的专家做所有必要的工作为了货物的快速释放。
%p 海关清关圣彼得堡是根据关键在海关机会皮卡产品组织和紧迫的问题。 货物通关，在抵达圣彼得堡的海运，空运，铁路和公路。
%p 为什么要信任»Hermes»公司商业品通关？
%p 我们提供最好的价格和市场上的合作，最灵活的条款;
%p 我们提供全方位的服务交付“门到门”从世界各地;
%p 我们提供在全俄罗斯工作，将货物运到全国任何地区;
%p 我们提供物流计划，在各个方向运行;
%p 我们已经建立了圣彼得堡的海关工作人员接触;
%p 我们提供附加服务：产品合格证，保险等。
%p 现在就联系我们就预定交付和商业货品清关免费咨询。我们将能够为您提供在市场上合作的最有利的条件。

app/views/sitemaps/index.xml.haml
- base_url = "http://#{request.host_with_port}"
!!! XML
%urlset{:xmlns => "http://www.sitemaps.org/schemas/sitemap/0.9"}
  -# default locale
  - @blogs.each do |blog|
    %url
      %loc #{base_url}/内容/#{blog.to_param}
      %lastmod=blog.updated_at.strftime("%Y-%m-%d")
      %changefreq monthly
      %priority 0.9
  - @static_pages.each do |page| 
    %url
      %loc #{base_url}/#{page}
      %changefreq monthly
      %priority 0.9